### ISSUE TITLE
Data too long for column 'data' at row 1

### ISSUE THREAD

**Issue by charlesbrandt** [bobintetley/asm3#305]
We're running version 40u of asm3. We recently started seeing a problem when accessing "Settings -> Options". After clicking the button, an alert says: "Internal Server Error". 

This was working yesterday, so I suspect there was a setting that was changed between now and then, but I'm at a loss for which one.  

It seems that this is being caused by an unusually large session value. I see the following traceback in our error.log:

```
Traceback (most recent call last):, referer: https://shelter.bloomington.in.gov/main
  File "/usr/lib/python2.7/dist-packages/web/application.py", line 237, in process, referer: https://shelter.bloomington.in.gov/main
    return p(lambda: process(processors)), referer: https://shelter.bloomington.in.gov/main
  File "/usr/lib/python2.7/dist-packages/web/session.py", line 90, in _processor, referer: https://shelter.bloomington.in.gov/main
    self._save(), referer: https://shelter.bloomington.in.gov/main
  File "/usr/lib/python2.7/dist-packages/web/session.py", line 138, in _save, referer: https://shelter.bloomington.in.gov/main
    self.store[self.session_id] = dict(self._data), referer: https://shelter.bloomington.in.gov/main
  File "/usr/lib/python2.7/dist-packages/web/session.py", line 309, in __setitem__, referer: https://shelter.bloomington.in.gov/main
    self.db.update(self.table, where="session_id=$key", data=pickled, vars=locals()), referer: https://shelter.bloomington.in.gov/main
  File "/usr/lib/python2.7/dist-packages/web/db.py", line 883, in update, referer: https://shelter.bloomington.in.gov/main
    self._db_execute(db_cursor, query), referer: https://shelter.bloomington.in.gov/main
  File "/usr/lib/python2.7/dist-packages/web/db.py", line 587, in _db_execute, referer: https://shelter.bloomington.in.gov/main
    out = cur.execute(query, params), referer: https://shelter.bloomington.in.gov/main
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 226, in execute, referer: https://shelter.bloomington.in.gov/main
    self.errorhandler(self, exc, value), referer: https://shelter.bloomington.in.gov/main
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler, referer: https://shelter.bloomington.in.gov/main
    raise errorvalue, referer: https://shelter.bloomington.in.gov/main
DataError: (1406, "Data too long for column 'data' at row 1"), referer: https://shelter.bloomington.in.gov/main
, referer: https://shelter.bloomington.in.gov/main

```
We've considered increasing the size of the data field from 'text' to something larger, but we have concerns about any unintended side effects.

```
mysql> describe sessions;
+------------+-----------+------+-----+-------------------+-------+
| Field      | Type      | Null | Key | Default           | Extra |
+------------+-----------+------+-----+-------------------+-------+
| session_id | char(128) | NO   | PRI | NULL              |       |
| atime      | timestamp | NO   |     | CURRENT_TIMESTAMP |       |
| data       | text      | YES  |     | NULL              |       |
+------------+-----------+------+-----+-------------------+-------+
```

Any thoughts or suggestions?

**Comment by bobintetley** [comment]
Hi, I wouldn't bother - storing sessions in the database is horribly inefficient and will very negatively impact your database performance. It looks like the error is caused by a TEXT type being too small in MySQL - change it to LONGTEXT to fix it if you really want.

Looking at git logs, we ditched the facility to store sessions in the database altogether in favour of memcache or a built in dict (depending on whether sitedefs.MEMCACHED_SERVER is set) back in May, so taking a new cut of 40u will also fix it and give you a huge performance boost.

**Comment by charlesbrandt** [comment]
Thanks for the response. Switching to memcached solved this issue for us.
