### ISSUE TITLE
Internal server error when creating new contacts

### ISSUE THREAD

**Issue by julian-poidevin** [bobintetley/asm3#795]
Hello,

Running the latest version of ASM, sometime, when creating a contact and filling the fields :

- Title
- Name
- Surname
- Phone
- City
- Postal Code

I get an "Internal Servor Error", see details and console log below : 
![image](https://user-images.githubusercontent.com/8756421/80281790-f7cdb680-870d-11ea-813d-1b949cb97058.png)

I'll try to run ASM in debug mode to get more information on this error.

**Comment by julian-poidevin** [comment]
Here's the error log :

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/web/application.py", line 257, in process
    return self.handle()
  File "/usr/lib/python3/dist-packages/web/application.py", line 248, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/lib/python3/dist-packages/web/application.py", line 488, in _delegate
    return handle_class(cls)
  File "/usr/lib/python3/dist-packages/web/application.py", line 466, in handle_class
    return tocall(*args)
  File "/root/repo/asm3/src/code.py", line 353, in POST
    return getattr(self.__class__, "post_%s" % mode)(self, o)
  File "/root/repo/asm3/src/code.py", line 4612, in post_similar
    p = asm3.person.get_person_similar(dbo, email, mobile, surname, forenames, address)
  File "/root/repo/asm3/src/asm3/person.py", line 106, in get_person_similar
    mq = dbo.query(get_person_query(dbo) + " WHERE %s LIKE ?" % dbo.sql_atoi("o.MobileTelephone") , [str(asm3.utils.atoi(mobile))])
  File "/root/repo/asm3/src/asm3/dbms/base.py", line 572, in query
    raise err
  File "/root/repo/asm3/src/asm3/dbms/base.py", line 538, in query
    s.execute(sql, params)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 292, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1305, 'FUNCTION asm3_mce_db.REGEXP_REPLACE does not exist')

89.86.90.62:50195 - - [25/Apr/2020 16:04:09] "HTTP/1.1 POST /person_embed" - 500 Internal Server Error
```

**Comment by julian-poidevin** [comment]
When removing the mobile phone field it works, it seem coherent with the error log. The issue is related to the phone number.

**Comment by julian-poidevin** [comment]
For information, my `mysqld` version is :
```
root@vps759328:~/repo/asm3# mysqld --version
mysqld  Ver 5.7.29-0ubuntu0.18.04.1 for Linux on x86_64 ((Ubuntu))
```

I found this on [StackOverflow ](https://stackoverflow.com/a/52137988):

> REGEXP_REPLACE function was released in version 8.0.4, so updating to 8.0.12 solved the problem.

**Comment by julian-poidevin** [comment]
I don't have this issue if I create the contact without the phone, clic on "Create and Edit" and then adding the phone number.

**Comment by bobintetley** [comment]
The code that deduplicates people record looks at the phone number to see if you already have them on file. When doing this, the phone number search uses REGEXP_REPLACE to remove all but numbers from the phone number fields when comparing (so (333) 375-4444 would still match if you entered the number as 3333754444)

I didn't realise that REGEXP_REPLACE was a later addition to MySQL. So yes - you either need a MySQL that supports it or we add an option to disable it. Hasn't MariaDB 10+ been the standard in the last couple of versions of Ubuntu and Debian?

**Comment by julian-poidevin** [comment]
I'm not very familiar with MySQL, but I checked the version, it returns `5.7.29-0ubuntu0.18.04.1 (Ubuntu)` :

```
root@vps759328:~/repo/asm3# mysql -u root -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 42151
Server version: 5.7.29-0ubuntu0.18.04.1 (Ubuntu)
```

I'll try to update it and get back to you. Thanks

**Comment by julian-poidevin** [comment]
I updated MySQL from `5.7` to `8.x` using this tutorial : https://www.javacodemonk.com/upgrade-mysql-from-5-7-to-8-on-ubuntu-18-04-bd9b5e46

This is now fixed.

**Maybe you should provide some information in the README to recommend using MySQL >= 8.x ?**

Thanks !
