### ISSUE TITLE
Make error: building schema.js fails inserting default templateHTML rows

### ISSUE THREAD

**Issue by inghamn** [bobintetley/asm3#859]
When using the makefile to create an installable build, the make_db.py errors out when trying to insert the default html templates. This is for generating the schema.js file.

The sqlite schema that is created by dbupdate for the tempatehtml table does not have auto increment set for the ID.  However, dbupdate.add_html_template attempts to insert rows without an ID field.  The causes a unique constraint error.

Ubuntu 20.04
sqlite3
python3

```
Traceback (most recent call last):
  File "scripts/schema/make_db.py", line 24, in <module>
    asm3.dbupdate.install(dbo)
  File "/home/inghamn/Documents/Projects/asm3/scripts/schema/../../src/asm3/dbupdate.py", line 2563, in install
    install_default_templates(dbo)
  File "/home/inghamn/Documents/Projects/asm3/scripts/schema/../../src/asm3/dbupdate.py", line 2518, in install_default_templates
    add_html_template_from_files("animalviewadoptable")
  File "/home/inghamn/Documents/Projects/asm3/scripts/schema/../../src/asm3/dbupdate.py", line 2510, in add_html_template_from_files
    add_html_template(name, head, body, foot, 0)
  File "/home/inghamn/Documents/Projects/asm3/scripts/schema/../../src/asm3/dbupdate.py", line 2499, in add_html_template
    dbo.insert("templatehtml", {
  File "/home/inghamn/Documents/Projects/asm3/scripts/schema/../../src/asm3/dbms/base.py", line 433, in insert
    self.execute(sql, list(values.values()), override_lock=setOverrideDBLock)
  File "/home/inghamn/Documents/Projects/asm3/scripts/schema/../../src/asm3/dbms/base.py", line 312, in execute
    raise err
  File "/home/inghamn/Documents/Projects/asm3/scripts/schema/../../src/asm3/dbms/base.py", line 295, in execute
    s.execute(sql, params)
sqlite3.IntegrityError: UNIQUE constraint failed: templatehtml.ID
make: *** [Makefile:83: scripts/schema/schema.db] Error 1
```

**Comment by bobintetley** [comment]
It is using dbms/base.py/get_cache_id to generate the ID, which uses get_max_id for the first value to fill the cache.

Wondering if this is a race condition, do you have memcached installed?

**Comment by inghamn** [comment]
That could be what's going on.   I do not have memcached installed on my laptop where I'm doing the build.  It only gets installed on the server where we deploy to.

**Comment by inghamn** [comment]
Lots of the other DB inserts worked, though

**Comment by inghamn** [comment]
If something like memcache is required for the build, I wonder if I should be doing the build on the actual server where its going to be deployed.  This impacts how the Ansible deployment works and how we would try to build Docker images.

How do you typically do the build and deploy for your own deployments?  Is this something you build on the machine you're deploying to?

**Comment by bobintetley** [comment]
It *shouldn't* be, I'm just thinking that get_id_cache uses cachemem.py which in turn uses memcache if available and I think it is on my machine. It should fall back to an in memory dictionary if unavailable. It should not be critical for the build, but it's the only thing I can think of that's changed. I'll disable memcache and see if it affects my local build of schema.

**Comment by bobintetley** [comment]
... no, I guess not that. I stopped memcached and ran
```
rm scripts/schema/schema.db
make schema
```
no errors.

**Comment by bobintetley** [comment]
is this error repeatable if you delete schema.db and try again?

**Comment by bobintetley** [comment]
to answer your other question, no, this is a build time only thing it is not run on the deployment machines. The whole objective is to generate the static schema.js file, which is used for the autocomplete when editing SQL in the UI.

**Comment by inghamn** [comment]
On my laptop, I repeated the make after deleting schema.db and hit the same error.  I also cloned the project on the server and attempted a build there, triggering the same error.  The server is also Ubuntu 20.04.

I wonder if there is a change with the latest sqlite libraries.....

**Comment by bobintetley** [comment]
The fault must be id generation if the unique constraint is getting triggered. Just out of interest, what happens if you edit dbms/base.py and change the get_id function to call get_id_max instead of get_id_cache ?

**Comment by inghamn** [comment]
Changing to get_id_max returns a very different error at that point.  I'm wondering if there's another missing quote or some SQL syntax error somewhere....


```
INSERT INTO vaccinationtype (ID, VaccinationType, DefaultCost, IsRetired) VALUES (14, 'FECV/FeCoV', 0, 0)
# Generate a JSON schema of the database for use when editing
# SQL within the program
[schema] =============================
mkdir -p src/static/js/bundle
scripts/schema/schema.py > src/static/js/bundle/schema.js
0.0 (1): SELECT name FROM sqlite_master WHERE type='table' ORDER BY name
0.0 (2): pragma table_info(accounts)
0.0 (3): pragma table_info(accountsrole)
0.0 (4): pragma table_info(accountstrx)
0.0 (5): pragma table_info(additional)
0.0 (6): pragma table_info(additionalfield)
0.0 (7): pragma table_info(adoption)
0.0 (8): pragma table_info(animal)
0.0 (9): pragma table_info(animalcontrol)
0.0 (10): pragma table_info(animalcontrolanimal)
0.0 (11): pragma table_info(animalcontrolrole)
0.0 (12): pragma table_info(animalcost)
0.0 (13): pragma table_info(animaldiet)
0.0 (14): pragma table_info(animalfigures)
0.0 (15): pragma table_info(animalfiguresannual)
0.0 (16): pragma table_info(animalfound)
0.0 (17): pragma table_info(animallitter)
0.0 (18): pragma table_info(animallost)
0.0 (19): pragma table_info(animallostfoundmatch)
0.0 (20): pragma table_info(animalmedical)
0.0 (21): pragma table_info(animalmedicaltreatment)
0.0 (22): pragma table_info(animalname)
0.0 (23): pragma table_info(animalpublished)
0.0 (24): pragma table_info(animaltest)
0.0 (25): pragma table_info(animaltransport)
0.0 (26): pragma table_info(animaltype)
0.0 (27): pragma table_info(animalvaccination)
0.0 (28): pragma table_info(animalwaitinglist)
0.0 (29): pragma table_info(audittrail)
0.0 (30): pragma table_info(basecolour)
0.0 (31): pragma table_info(breed)
0.0 (32): pragma table_info(citationtype)
0.0 (33): pragma table_info(clinicappointment)
0.0 (34): pragma table_info(clinicinvoiceitem)
0.0 (35): pragma table_info(configuration)
0.0 (36): pragma table_info(costtype)
0.0 (37): pragma table_info(customreport)
0.0 (38): pragma table_info(customreportrole)
0.0 (39): pragma table_info(dbfs)
0.0 (40): pragma table_info(deathreason)
0.0 (41): pragma table_info(deletion)
0.0 (42): pragma table_info(diary)
0.0 (43): pragma table_info(diarytaskdetail)
0.0 (44): pragma table_info(diarytaskhead)
0.0 (45): pragma table_info(diet)
0.0 (46): pragma table_info(donationpayment)
0.0 (47): pragma table_info(donationtype)
0.0 (48): pragma table_info(entryreason)
0.0 (49): pragma table_info(incidentcompleted)
0.0 (50): pragma table_info(incidenttype)
0.0 (51): pragma table_info(internallocation)
0.0 (52): pragma table_info(jurisdiction)
0.0 (53): pragma table_info(licencetype)
0.0 (54): pragma table_info(lkanimalflags)
0.0 (55): pragma table_info(lkcoattype)
0.0 (56): pragma table_info(lkownerflags)
0.0 (57): pragma table_info(lksaccounttype)
0.0 (58): pragma table_info(lksclinicstatus)
0.0 (59): pragma table_info(lksdiarylink)
0.0 (60): pragma table_info(lksdonationfreq)
0.0 (61): pragma table_info(lksex)
0.0 (62): pragma table_info(lksfieldlink)
0.0 (63): pragma table_info(lksfieldtype)
0.0 (64): pragma table_info(lksize)
0.0 (65): pragma table_info(lksloglink)
0.0 (66): pragma table_info(lksmedialink)
0.0 (67): pragma table_info(lksmediatype)
0.0 (68): pragma table_info(lksmovementtype)
0.0 (69): pragma table_info(lksposneg)
0.0 (70): pragma table_info(lksrotatype)
0.0 (71): pragma table_info(lkstransportstatus)
0.0 (72): pragma table_info(lksyesno)
0.0 (73): pragma table_info(lksynun)
0.0 (74): pragma table_info(lksynunk)
0.0 (75): pragma table_info(lkurgency)
0.0 (76): pragma table_info(lkworktype)
0.0 (77): pragma table_info(log)
0.0 (78): pragma table_info(logtype)
0.0 (79): pragma table_info(media)
0.0 (80): pragma table_info(medicalprofile)
0.0 (81): pragma table_info(messages)
0.0 (82): pragma table_info(onlineform)
0.0 (83): pragma table_info(onlineformfield)
0.0 (84): pragma table_info(onlineformincoming)
0.0 (85): pragma table_info(owner)
0.0 (86): pragma table_info(ownercitation)
0.0 (87): pragma table_info(ownerdonation)
0.0 (88): pragma table_info(ownerinvestigation)
0.0 (89): pragma table_info(ownerlicence)
0.0 (90): pragma table_info(ownerlookingfor)
0.0 (91): pragma table_info(ownerrota)
0.0 (92): pragma table_info(ownertraploan)
0.0 (93): pragma table_info(ownervoucher)
0.0 (94): pragma table_info(pickuplocation)
0.0 (95): pragma table_info(primarykey)
0.0 (96): pragma table_info(publishlog)
0.0 (97): pragma table_info(reservationstatus)
0.0 (98): pragma table_info(role)
0.0 (99): pragma table_info(site)
0.0 (100): pragma table_info(species)
0.0 (101): pragma table_info(stocklevel)
0.0 (102): pragma table_info(stocklocation)
0.0 (103): pragma table_info(stockusage)
0.0 (104): pragma table_info(stockusagetype)
0.0 (105): pragma table_info(templatedocument)
0.0 (106): pragma table_info(templatehtml)
0.0 (107): pragma table_info(testresult)
0.0 (108): pragma table_info(testtype)
0.0 (109): pragma table_info(transporttype)
0.0 (110): pragma table_info(traptype)
0.0 (111): pragma table_info(userrole)
0.0 (112): pragma table_info(users)
0.0 (113): pragma table_info(vaccinationtype)
0.0 (114): pragma table_info(voucher)
0.0 (115): pragma table_info(adoption)
0.0 (116): pragma table_info(animal)
0.0 (117): pragma table_info(animalcontrol)
0.0 (118): pragma table_info(animalfound)
0.0 (119): pragma table_info(animallost)
0.0 (120): pragma table_info(animalmedicaltreatment)
0.0 (121): pragma table_info(animaltest)
0.0 (122): pragma table_info(animalvaccination)
0.0 (123): pragma table_info(animalwaitinglist)
0.0 (124): pragma table_info(owner)
0.0 (125): pragma table_info(ownercitation)
0.0 (126): pragma table_info(ownerdonation)
0.0 (127): pragma table_info(ownerlicence)
0.0 (128): pragma table_info(ownertraploan)
0.0 (129): pragma table_info(ownervoucher)
```

**Comment by inghamn** [comment]
Maybe something about some unexpected file path in dbupdate.add_html_template_from_files().  It's trying to read text files from dbo.installpath, then use the contents of those files in SQL insert statements.

**Comment by bobintetley** [comment]
What's the error? That looks like the expected output and you should now have a src/static/js/bundle/schema.js file.

**Comment by inghamn** [comment]
Ah, okay I took all that text to be an error.  So, yes, the build did work, then; including producing the schema.js file.

**Comment by bobintetley** [comment]
I think the behaviour of cachemem._dict_increment isn't matching memcache's incr behaviour, not sure why it worked for me before when I disabled memcache. Thanks for the heads up.

**Comment by inghamn** [comment]
Thanks for looking into it so quickly.  I wasn't expecting such a quick turnaround! :)

**Comment by bobintetley** [comment]
Got it, the behaviour is correct, the return value is wrong. Thanks for tracking that down!
