### ISSUE TITLE
Online forms: error when attaching people to incoming form

### ISSUE THREAD

**Issue by inghamn** [bobintetley/asm3#867]
When attempting to attach a person to an Incoming Form, python crashes out with an type error.  utils.py write_binary_file() is passed string data, and the function is expecting binary data.

onlineform.create_person is reading attributes from the POST and passing them through as strings.

onlineform.get_onlineformincoming_html_print returns the form as a string, which is then attempted to be written to a file as binary data.

This is on Ubuntu 20.04 with python3

```
Traceback (most recent call last):, referer: https://shelter-test.bloomington.in.gov/asm/onlineform_incoming
  File "/usr/lib/python3/dist-packages/web/application.py", line 289, in process, referer: https://shelter-test.bloomington.in.gov/asm/onlineform_incoming
    return self.handle(), referer: https://shelter-test.bloomington.in.gov/asm/onlineform_incoming
  File "/usr/lib/python3/dist-packages/web/application.py", line 280, in handle, referer: https://shelter-test.bloomington.in.gov/asm/onlineform_incoming
    return self._delegate(fn, self.fvars, args), referer: https://shelter-test.bloomington.in.gov/asm/onlineform_incoming
  File "/usr/lib/python3/dist-packages/web/application.py", line 530, in _delegate, referer: https://shelter-test.bloomington.in.gov/asm/onlineform_incoming
    return handle_class(cls), referer: https://shelter-test.bloomington.in.gov/asm/onlineform_incoming
  File "/usr/lib/python3/dist-packages/web/application.py", line 508, in handle_class, referer: https://shelter-test.bloomington.in.gov/asm/onlineform_incoming
    return tocall(*args), referer: https://shelter-test.bloomington.in.gov/asm/onlineform_incoming
  File "/srv/sites/asm/src/code.py", line 364, in POST, referer: https://shelter-test.bloomington.in.gov/asm/onlineform_incoming
    return getattr(self.__class__, "post_%s" % mode)(self, o), referer: https://shelter-test.bloomington.in.gov/asm/onlineform_incoming
  File "/srv/sites/asm/src/code.py", line 4218, in post_person, referer: https://shelter-test.bloomington.in.gov/asm/onlineform_incoming
    collationid, personid, personname, status = asm3.onlineform.create_person(o.dbo, o.user, pid), referer: https://shelter-test.bloomington.in.gov/asm/onlineform_incoming
  File "/srv/sites/asm/src/asm3/onlineform.py", line 1048, in create_person, referer: https://shelter-test.bloomington.in.gov/asm/onlineform_incoming
    attach_form(dbo, username, asm3.media.PERSON, personid, collationid), referer: https://shelter-test.bloomington.in.gov/asm/onlineform_incoming
  File "/srv/sites/asm/src/asm3/onlineform.py", line 876, in attach_form, referer: https://shelter-test.bloomington.in.gov/asm/onlineform_incoming
    asm3.media.create_document_media(dbo, username, linktype, linkid, formname, formhtml ), referer: https://shelter-test.bloomington.in.gov/asm/onlineform_incoming
  File "/srv/sites/asm/src/asm3/media.py", line 494, in create_document_media, referer: https://shelter-test.bloomington.in.gov/asm/onlineform_incoming
    dbfsid = asm3.dbfs.put_string(dbo, name, path, content), referer: https://shelter-test.bloomington.in.gov/asm/onlineform_incoming
  File "/srv/sites/asm/src/asm3/dbfs.py", line 335, in put_string, referer: https://shelter-test.bloomington.in.gov/asm/onlineform_incoming
    o.put(dbfsid, name, contents), referer: https://shelter-test.bloomington.in.gov/asm/onlineform_incoming
  File "/srv/sites/asm/src/asm3/dbfs.py", line 53, in put, referer: https://shelter-test.bloomington.in.gov/asm/onlineform_incoming
    return self.o.put(dbfsid, filename, filedata), referer: https://shelter-test.bloomington.in.gov/asm/onlineform_incoming
  File "/srv/sites/asm/src/asm3/dbfs.py", line 115, in put, referer: https://shelter-test.bloomington.in.gov/asm/onlineform_incoming
    asm3.utils.write_binary_file(filepath, filedata), referer: https://shelter-test.bloomington.in.gov/asm/onlineform_incoming
  File "/srv/sites/asm/src/asm3/utils.py", line 1233, in write_binary_file, referer: https://shelter-test.bloomington.in.gov/asm/onlineform_incoming
    f.write(data), referer: https://shelter-test.bloomington.in.gov/asm/onlineform_incoming
TypeError: a bytes-like object is required, not 'str', referer: https://shelter-test.bloomington.in.gov/asm/onlineform_incoming
, referer: https://shelter-test.bloomington.in.gov/asm/onlineform_incoming

```

**Comment by inghamn** [comment]
Now that asm supports Python3, is it worth starting to use type annotations to surface problems like this?

**Comment by bobintetley** [comment]
Thanks for the heads up. I think this has happened partly because the File DBFS driver is the least used (I tend to use B64 locally and S3 in production). media.create_document_media is passing through the content without making sure it's a byte str. In this case, we already have a unicode str containing the HTML of the form but we want bytes for storage in the file. We use UTF-8 for everything so it's fairly easy to switch between the two.

**Comment by inghamn** [comment]
Thanks for taking a look. :)
